### ISSUE TITLE
Allow editing & sharing projects

### ISSUE THREAD

**Issue by PullJosh** [PullJosh/scratch-js-website#6]
*I neglected scratch-js for a while, but I have time now! 🎉*

*I'm planning to do an advertising push to make sure everybody knows about scratch-js, but first the whole project needs a bit more polish.*

The final important job before really publicizing scratch-js is making it easy to edit and share projects. There are a few options here:
* ✔️ **[Glitch](https://glitch.com/):** Strongest community and most Scratch-like vibes.
* ❌ **[Codepen](https://codepen.io/):** Free-tier users are limited to one project.
* ❌ **[CodeSandbox](https://codesandbox.io/):** Very little community focus. Sharing projects isn't really a thing.
* *Any other recommendations?*

**The problem is that Glitch doesn't have an API for making projects.** I'm hoping that it's possible to hijack the "import from Github" process by serving projects as read-only git repos on the scratch-js website.

**Comment by PullJosh** [comment]
Actually, the more I look into Glitch, the less of a community I see. :/ There really is nothing like Scratch, is there?

**Comment by PullJosh** [comment]
Another option is to use CodeSandbox (which provides [an API](https://codesandbox.io/docs/importing#define-api) for creating projects), and handle the sharing and community elements separately.

I've already been thinking about this for a bit: https://twitter.com/PullJosh/status/1268715133540487168

The idea is to build a website that allows people to share things they're creating (not just scratch-js projects!) as URLs. Sort of like Reddit, but only for OC, and a bit more kid-friendly, which is nice for post-Scratch folks.

**Comment by Explosion-Scratch** [comment]
If you want something like scratch to advertise on why not just use scratch?

**Comment by PullJosh** [comment]
That's... incredibly reasonable. A forum post should do the trick.

**Comment by Explosion-Scratch** [comment]
I'd do show and tell, AT, and then share a project and put something in your siggy :)

**Comment by PullJosh** [comment]
Edit with CodeSandbox has been implemented in 24c11a409a830e24348256b1e6d9858ee1ac5e10. Community forum post and such coming soon, but first I want to record a video explaining scratch-js.
